apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo
  namespace: test
  labels:
    app: odoo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      labels:
        app: odoo
      annotations:
        # ðŸ§  K8up backup: dumps both database and filestore to stdout
        # Using "-" as output means "write to stdout", perfect for restic
        k8up.io/backupcommand: /bin/bash -c 'curl -s -X POST --data-raw "master_pwd=${MASTER_PASSWORD}&name=${ODOO_DATABASE}&backup_format=zip" -o - http://localhost:8069/web/database/backup'

    spec:
      containers:
        - name: odoo
          image: odoo:18.0
          ports:
            - containerPort: 8069
              name: http
          env:
            - name: MASTER_PASSWORD
              value: odoo
            - name: ODOO_DATABASE
              value: odoo
            - name: HOST
              value: postgres.test.svc.cluster.local
            - name: USER
              valueFrom:
                secretKeyRef:
                  name: backup-test-creds
                  key: db-username
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backup-test-creds
                  key: db-password
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: odoo
  name: odoo
  namespace: test
spec:
  ports:
    - name: http
      port: 8069
      targetPort: 8069
    - name: websocket
      port: 8072
      targetPort: 8072
  selector:
    app: odoo
